on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
      - uses: actions/checkout@v3   
      - name: "login to docker hub"
        run: docker login --username ${{ secrets.secret1 }} --password ${{ secrets.secret2 }}
      - name: "creating image"
        run: docker build -t rolarasheed/imagerola2 .
      - name: "pushing image"
        run: docker push rolarasheed/imagerola2     
